service:
  name: softnote

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-s3-local
  - serverless-dynamodb-local
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    DYNAMODB_TABLE: ${self:service.name}-${opt:stage, self:provider.stage}-refresh-tokens
    USER_CONFIGURATION_TABLE: ${self:service.name}-${opt:stage, self:provider.stage}-user-configuration
    S3_IMAGE_BUCKET: ${self:service.name}-${opt:stage, self:provider.stage}-images
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - s3:PutObject
        - s3:GetObject
      Resource:
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}'
        - 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_CONFIGURATION_TABLE}'
        - 'arn:aws:s3:::${self:provider.environment.S3_IMAGE_BUCKET}/*'
  apiGateway:
    binaryMediaTypes:
      - 'application/x-git-upload-pack-result'
      - 'application/x-git-receive-pack-result'
      - 'application/x-git-receive-pack-request'

custom:
  webpack:
    includeModules: true
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      migrate: true
  s3:
    host: localhost
    directory: /tmp
    cors: ./s3-cors.xml
    allowMismatchedSignatures: true

functions:
  webhook:
    handler: src/handlers.webhook
    events:
      - http:
          method: post
          path: webhook
  proxy:
    handler: src/handlers.proxy
    events:
      - http:
          method: ANY
          path: proxy/{proxy+}
          cors:
            origins:
              - 'http://localhost:8080'
              - 'http://noted-development.s3-website-eu-west-1.amazonaws.com'
              - 'https://notehub.xyz'
              - 'https://www.notehub.xyz'
            allowCredentials: true
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Owner
  graphql:
    handler: src/handlers.graphql
    timeout: 10
    events:
      - http:
          method: ANY
          path: graphql
          cors:
            origins:
              - 'http://noted-development.s3-website-eu-west-1.amazonaws.com'
              - 'https://notehub.xyz'
              - 'https://www.notehub.xyz'
              - 'http://localhost:8080'
            allowCredentials: true
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Owner
  refresh:
    handler: src/handlers.refresh
    timeout: 10
    events:
      - http:
          method: GET
          path: refresh
          cors:
            origins:
              - 'http://noted-development.s3-website-eu-west-1.amazonaws.com'
              - 'https://notehub.xyz'
              - 'https://www.notehub.xyz'
              - 'http://localhost:8080'
            allowCredentials: true
            headers:
              - Authorization

resources:
  Resources:
    SigningKeyDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    ConfigurationDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.USER_CONFIGURATION_TABLE}
    StorageBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:provider.environment.S3_IMAGE_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - 'http://localhost:8080'
                - 'http://noted-development.s3-website-eu-west-1.amazonaws.com'
                - 'https://notehub.xyz'
                - 'https://www.notehub.xyz'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              MaxAge: 3000