export enum APOLLO_ERRORS {
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  JWT_EXPIRED = 'JWT_EXPIRED',
  JWT_SIGNATURE_MISMATCH = 'JWT_SIGNATURE_MISMATCH',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_NOT_VALID = 'REFRESH_TOKEN_NOT_VALID',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}